import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { FaFilePdf } from "react-icons/fa";

export const PDFReportButtonAdmin = ({ users, currentUser }) => {
  const generatePDF = () => {
    const doc = new jsPDF();
    const date = new Date();
    const adminName = currentUser?.username || "Admin";

    // ===== HEADER SECTION =====
    doc.setFontSize(18);
    doc.setTextColor(40, 53, 147);
    doc.text("USER MANAGEMENT REPORT", 105, 20, { align: "center" });

    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Generated by: ${adminName}`, 15, 30);
    doc.text(`Date: ${date.toLocaleDateString()}`, 15, 35);
    doc.text(`Time: ${date.toLocaleTimeString()}`, 15, 40);

    // Horizontal divider
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 45, 195, 45);

    // ===== TABLE SECTION =====
    const headers = [["No.", "Username", "Email", "Admin", "Join Date"]];
    const data = users.map((user, index) => [
      index + 1,
      user.username,
      user.email,
      {
        content: user.isAdmin ? "Yes" : "No",
        styles: { textColor: user.isAdmin ? [0, 128, 0] : [255, 0, 0] },
      },
      new Date(user.createdAt).toLocaleDateString(),
    ]);

    autoTable(doc, {
      head: headers,
      body: data,
      startY: 50,
      headStyles: {
        fillColor: [40, 53, 147],
        textColor: 255,
        fontSize: 10,
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
        valign: "middle",
        cellWidth: "wrap",
      },
      columnStyles: {
        3: { cellWidth: 20 }, // Set specific width for Admin column
      },
      didParseCell: (data) => {
        // Apply styles to Admin column
        if (data.column.index === 3 && data.cell.raw) {
          data.cell.styles = data.cell.styles || {};
          data.cell.styles.fontStyle =
            data.cell.raw.content === "Yes" ? "bold" : "normal";
        }
      },
    });

    // ===== FOOTER SECTION =====
    const finalY = doc.lastAutoTable.finalY + 15;

    doc.setFontSize(10);
    doc.text("Authorized by:", 15, finalY);
    doc.text("_________________________", 15, finalY + 10);
    doc.text(adminName, 15, finalY + 20);
    doc.text("System Administrator", 15, finalY + 25);

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Confidential - System Generated Report", 105, 285, {
      align: "center",
    });

    doc.save(
      `users-report-${adminName}-${date.toISOString().slice(0, 10)}.pdf`
    );
  };

  return (
    <button
      onClick={generatePDF}
      className="flex items-center gap-2 px-4 py-2 text-white transition-colors bg-red-600 rounded-lg hover:bg-red-700"
    >
      <FaFilePdf /> Export PDF
    </button>
  );
};
